#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("TheGovernator.Resource", IsApplication=true)]

namespace TheGovernator
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f040006
			public const int button_chocolates = 2130968582;
			
			// aapt resource value: 0x7f040024
			public const int button_deadpeople = 2130968612;
			
			// aapt resource value: 0x7f04000c
			public const int button_dreams = 2130968588;
			
			// aapt resource value: 0x7f04002a
			public const int button_gohome = 2130968618;
			
			// aapt resource value: 0x7f04001a
			public const int button_hello = 2130968602;
			
			// aapt resource value: 0x7f040004
			public const int button_itsme = 2130968580;
			
			// aapt resource value: 0x7f040028
			public const int button_likehome = 2130968616;
			
			// aapt resource value: 0x7f040022
			public const int button_littlefriend = 2130968610;
			
			// aapt resource value: 0x7f04001c
			public const int button_neverhungry = 2130968604;
			
			// aapt resource value: 0x7f040012
			public const int button_precious = 2130968594;
			
			// aapt resource value: 0x7f04000a
			public const int button_theforce = 2130968586;
			
			// aapt resource value: 0x7f040014
			public const int button_wakeup = 2130968596;
			
			// aapt resource value: 0x7f040000
			public const int linearLayoutX = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int linearLayoutY1 = 2130968577;
			
			// aapt resource value: 0x7f04001e
			public const int linearLayoutY10 = 2130968606;
			
			// aapt resource value: 0x7f04001f
			public const int linearLayoutY11 = 2130968607;
			
			// aapt resource value: 0x7f040020
			public const int linearLayoutY12 = 2130968608;
			
			// aapt resource value: 0x7f040026
			public const int linearLayoutY13 = 2130968614;
			
			// aapt resource value: 0x7f04002c
			public const int linearLayoutY14 = 2130968620;
			
			// aapt resource value: 0x7f040002
			public const int linearLayoutY2 = 2130968578;
			
			// aapt resource value: 0x7f040008
			public const int linearLayoutY3 = 2130968584;
			
			// aapt resource value: 0x7f04000e
			public const int linearLayoutY4 = 2130968590;
			
			// aapt resource value: 0x7f04000f
			public const int linearLayoutY5 = 2130968591;
			
			// aapt resource value: 0x7f040010
			public const int linearLayoutY6 = 2130968592;
			
			// aapt resource value: 0x7f040016
			public const int linearLayoutY7 = 2130968598;
			
			// aapt resource value: 0x7f040017
			public const int linearLayoutY8 = 2130968599;
			
			// aapt resource value: 0x7f040018
			public const int linearLayoutY9 = 2130968600;
			
			// aapt resource value: 0x7f040005
			public const int padding1 = 2130968581;
			
			// aapt resource value: 0x7f040019
			public const int padding10 = 2130968601;
			
			// aapt resource value: 0x7f04001b
			public const int padding11 = 2130968603;
			
			// aapt resource value: 0x7f04001d
			public const int padding12 = 2130968605;
			
			// aapt resource value: 0x7f040021
			public const int padding13 = 2130968609;
			
			// aapt resource value: 0x7f040023
			public const int padding14 = 2130968611;
			
			// aapt resource value: 0x7f040025
			public const int padding15 = 2130968613;
			
			// aapt resource value: 0x7f040029
			public const int padding16 = 2130968617;
			
			// aapt resource value: 0x7f040027
			public const int padding17 = 2130968615;
			
			// aapt resource value: 0x7f04002b
			public const int padding18 = 2130968619;
			
			// aapt resource value: 0x7f040007
			public const int padding2 = 2130968583;
			
			// aapt resource value: 0x7f040003
			public const int padding3 = 2130968579;
			
			// aapt resource value: 0x7f04000d
			public const int padding4 = 2130968589;
			
			// aapt resource value: 0x7f04000b
			public const int padding5 = 2130968587;
			
			// aapt resource value: 0x7f040009
			public const int padding6 = 2130968585;
			
			// aapt resource value: 0x7f040011
			public const int padding7 = 2130968593;
			
			// aapt resource value: 0x7f040013
			public const int padding8 = 2130968595;
			
			// aapt resource value: 0x7f040015
			public const int padding9 = 2130968597;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f020000
			public const int Main = 2130837504;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f030000
			public const int app_name = 2130903040;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
