#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("TheGovernator.Resource", IsApplication=true)]

namespace TheGovernator
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010000
			public const int constraintSet = 2130771968;
			
			// aapt resource value: 0x7f010001
			public const int layout_constraintBaseline_creator = 2130771969;
			
			// aapt resource value: 0x7f010002
			public const int layout_constraintBaseline_toBaselineOf = 2130771970;
			
			// aapt resource value: 0x7f010003
			public const int layout_constraintBottom_creator = 2130771971;
			
			// aapt resource value: 0x7f010004
			public const int layout_constraintBottom_toBottomOf = 2130771972;
			
			// aapt resource value: 0x7f010005
			public const int layout_constraintBottom_toTopOf = 2130771973;
			
			// aapt resource value: 0x7f010006
			public const int layout_constraintDimensionRatio = 2130771974;
			
			// aapt resource value: 0x7f010007
			public const int layout_constraintEnd_toEndOf = 2130771975;
			
			// aapt resource value: 0x7f010008
			public const int layout_constraintEnd_toStartOf = 2130771976;
			
			// aapt resource value: 0x7f010009
			public const int layout_constraintGuide_begin = 2130771977;
			
			// aapt resource value: 0x7f01000a
			public const int layout_constraintGuide_end = 2130771978;
			
			// aapt resource value: 0x7f01000b
			public const int layout_constraintGuide_percent = 2130771979;
			
			// aapt resource value: 0x7f01000c
			public const int layout_constraintHeight_default = 2130771980;
			
			// aapt resource value: 0x7f01000d
			public const int layout_constraintHeight_max = 2130771981;
			
			// aapt resource value: 0x7f01000e
			public const int layout_constraintHeight_min = 2130771982;
			
			// aapt resource value: 0x7f01000f
			public const int layout_constraintHorizontal_bias = 2130771983;
			
			// aapt resource value: 0x7f010010
			public const int layout_constraintHorizontal_chainStyle = 2130771984;
			
			// aapt resource value: 0x7f010011
			public const int layout_constraintHorizontal_weight = 2130771985;
			
			// aapt resource value: 0x7f010012
			public const int layout_constraintLeft_creator = 2130771986;
			
			// aapt resource value: 0x7f010013
			public const int layout_constraintLeft_toLeftOf = 2130771987;
			
			// aapt resource value: 0x7f010014
			public const int layout_constraintLeft_toRightOf = 2130771988;
			
			// aapt resource value: 0x7f010015
			public const int layout_constraintRight_creator = 2130771989;
			
			// aapt resource value: 0x7f010016
			public const int layout_constraintRight_toLeftOf = 2130771990;
			
			// aapt resource value: 0x7f010017
			public const int layout_constraintRight_toRightOf = 2130771991;
			
			// aapt resource value: 0x7f010018
			public const int layout_constraintStart_toEndOf = 2130771992;
			
			// aapt resource value: 0x7f010019
			public const int layout_constraintStart_toStartOf = 2130771993;
			
			// aapt resource value: 0x7f01001a
			public const int layout_constraintTop_creator = 2130771994;
			
			// aapt resource value: 0x7f01001b
			public const int layout_constraintTop_toBottomOf = 2130771995;
			
			// aapt resource value: 0x7f01001c
			public const int layout_constraintTop_toTopOf = 2130771996;
			
			// aapt resource value: 0x7f01001d
			public const int layout_constraintVertical_bias = 2130771997;
			
			// aapt resource value: 0x7f01001e
			public const int layout_constraintVertical_chainStyle = 2130771998;
			
			// aapt resource value: 0x7f01001f
			public const int layout_constraintVertical_weight = 2130771999;
			
			// aapt resource value: 0x7f010020
			public const int layout_constraintWidth_default = 2130772000;
			
			// aapt resource value: 0x7f010021
			public const int layout_constraintWidth_max = 2130772001;
			
			// aapt resource value: 0x7f010022
			public const int layout_constraintWidth_min = 2130772002;
			
			// aapt resource value: 0x7f010023
			public const int layout_editor_absoluteX = 2130772003;
			
			// aapt resource value: 0x7f010024
			public const int layout_editor_absoluteY = 2130772004;
			
			// aapt resource value: 0x7f010025
			public const int layout_goneMarginBottom = 2130772005;
			
			// aapt resource value: 0x7f010026
			public const int layout_goneMarginEnd = 2130772006;
			
			// aapt resource value: 0x7f010027
			public const int layout_goneMarginLeft = 2130772007;
			
			// aapt resource value: 0x7f010028
			public const int layout_goneMarginRight = 2130772008;
			
			// aapt resource value: 0x7f010029
			public const int layout_goneMarginStart = 2130772009;
			
			// aapt resource value: 0x7f01002a
			public const int layout_goneMarginTop = 2130772010;
			
			// aapt resource value: 0x7f01002b
			public const int layout_optimizationLevel = 2130772011;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int chocolates_icon = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int chocolates_icon_X = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int chocolates_LS = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int chocolates_P = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int dead_people_icon = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int dead_people_icon_X = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int dead_people_LS = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int dead_people_P = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int dreams_icon = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int dreams_icon_X = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int dreams_LS = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int dreams_P = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int force_icon = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int force_icon_X = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int force_LS = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int force_P = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int go_home_icon = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int go_home_icon_X = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int go_home_LS = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int go_home_P = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int hello_icon = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int hello_icon_X = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int hello_LS = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int hello_P = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int its_me_icon = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int its_me_icon_X = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int its_me_LS = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int its_me_P = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int like_home_icon = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int like_home_icon_X = 2130837533;
			
			// aapt resource value: 0x7f02001e
			public const int like_home_LS = 2130837534;
			
			// aapt resource value: 0x7f02001f
			public const int like_home_P = 2130837535;
			
			// aapt resource value: 0x7f020020
			public const int little_friend_icon = 2130837536;
			
			// aapt resource value: 0x7f020021
			public const int little_friend_icon_X = 2130837537;
			
			// aapt resource value: 0x7f020022
			public const int little_friend_LS = 2130837538;
			
			// aapt resource value: 0x7f020023
			public const int little_friend_P = 2130837539;
			
			// aapt resource value: 0x7f020024
			public const int never_hungry_icon = 2130837540;
			
			// aapt resource value: 0x7f020025
			public const int never_hungry_icon_X = 2130837541;
			
			// aapt resource value: 0x7f020026
			public const int never_hungry_LS = 2130837542;
			
			// aapt resource value: 0x7f020027
			public const int never_hungry_P = 2130837543;
			
			// aapt resource value: 0x7f020028
			public const int play_icon = 2130837544;
			
			// aapt resource value: 0x7f020029
			public const int play_icon_X = 2130837545;
			
			// aapt resource value: 0x7f02002a
			public const int precious_icon = 2130837546;
			
			// aapt resource value: 0x7f02002b
			public const int precious_icon_X = 2130837547;
			
			// aapt resource value: 0x7f02002c
			public const int precious_LS = 2130837548;
			
			// aapt resource value: 0x7f02002d
			public const int precious_P = 2130837549;
			
			// aapt resource value: 0x7f02002e
			public const int splash_screen = 2130837550;
			
			// aapt resource value: 0x7f02002f
			public const int wake_up_icon = 2130837551;
			
			// aapt resource value: 0x7f020030
			public const int wake_up_icon_X = 2130837552;
			
			// aapt resource value: 0x7f020031
			public const int wake_up_LS = 2130837553;
			
			// aapt resource value: 0x7f020032
			public const int wake_up_P = 2130837554;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060005
			public const int all = 2131099653;
			
			// aapt resource value: 0x7f060036
			public const int background = 2131099702;
			
			// aapt resource value: 0x7f060006
			public const int basic = 2131099654;
			
			// aapt resource value: 0x7f06000f
			public const int button_chocolates = 2131099663;
			
			// aapt resource value: 0x7f06002d
			public const int button_deadpeople = 2131099693;
			
			// aapt resource value: 0x7f060015
			public const int button_dreams = 2131099669;
			
			// aapt resource value: 0x7f060033
			public const int button_gohome = 2131099699;
			
			// aapt resource value: 0x7f060023
			public const int button_hello = 2131099683;
			
			// aapt resource value: 0x7f06000d
			public const int button_itsme = 2131099661;
			
			// aapt resource value: 0x7f060031
			public const int button_likehome = 2131099697;
			
			// aapt resource value: 0x7f06002b
			public const int button_littlefriend = 2131099691;
			
			// aapt resource value: 0x7f060025
			public const int button_neverhungry = 2131099685;
			
			// aapt resource value: 0x7f06001b
			public const int button_precious = 2131099675;
			
			// aapt resource value: 0x7f060013
			public const int button_theforce = 2131099667;
			
			// aapt resource value: 0x7f06001d
			public const int button_wakeup = 2131099677;
			
			// aapt resource value: 0x7f060007
			public const int chains = 2131099655;
			
			// aapt resource value: 0x7f060037
			public const int imageView1 = 2131099703;
			
			// aapt resource value: 0x7f060009
			public const int linearLayoutX = 2131099657;
			
			// aapt resource value: 0x7f06000a
			public const int linearLayoutY1 = 2131099658;
			
			// aapt resource value: 0x7f060027
			public const int linearLayoutY10 = 2131099687;
			
			// aapt resource value: 0x7f060028
			public const int linearLayoutY11 = 2131099688;
			
			// aapt resource value: 0x7f060029
			public const int linearLayoutY12 = 2131099689;
			
			// aapt resource value: 0x7f06002f
			public const int linearLayoutY13 = 2131099695;
			
			// aapt resource value: 0x7f060035
			public const int linearLayoutY14 = 2131099701;
			
			// aapt resource value: 0x7f06000b
			public const int linearLayoutY2 = 2131099659;
			
			// aapt resource value: 0x7f060011
			public const int linearLayoutY3 = 2131099665;
			
			// aapt resource value: 0x7f060017
			public const int linearLayoutY4 = 2131099671;
			
			// aapt resource value: 0x7f060018
			public const int linearLayoutY5 = 2131099672;
			
			// aapt resource value: 0x7f060019
			public const int linearLayoutY6 = 2131099673;
			
			// aapt resource value: 0x7f06001f
			public const int linearLayoutY7 = 2131099679;
			
			// aapt resource value: 0x7f060020
			public const int linearLayoutY8 = 2131099680;
			
			// aapt resource value: 0x7f060021
			public const int linearLayoutY9 = 2131099681;
			
			// aapt resource value: 0x7f060008
			public const int none = 2131099656;
			
			// aapt resource value: 0x7f060003
			public const int packed = 2131099651;
			
			// aapt resource value: 0x7f06000e
			public const int padding1 = 2131099662;
			
			// aapt resource value: 0x7f060022
			public const int padding10 = 2131099682;
			
			// aapt resource value: 0x7f060024
			public const int padding11 = 2131099684;
			
			// aapt resource value: 0x7f060026
			public const int padding12 = 2131099686;
			
			// aapt resource value: 0x7f06002a
			public const int padding13 = 2131099690;
			
			// aapt resource value: 0x7f06002c
			public const int padding14 = 2131099692;
			
			// aapt resource value: 0x7f06002e
			public const int padding15 = 2131099694;
			
			// aapt resource value: 0x7f060032
			public const int padding16 = 2131099698;
			
			// aapt resource value: 0x7f060030
			public const int padding17 = 2131099696;
			
			// aapt resource value: 0x7f060034
			public const int padding18 = 2131099700;
			
			// aapt resource value: 0x7f060010
			public const int padding2 = 2131099664;
			
			// aapt resource value: 0x7f06000c
			public const int padding3 = 2131099660;
			
			// aapt resource value: 0x7f060016
			public const int padding4 = 2131099670;
			
			// aapt resource value: 0x7f060014
			public const int padding5 = 2131099668;
			
			// aapt resource value: 0x7f060012
			public const int padding6 = 2131099666;
			
			// aapt resource value: 0x7f06001a
			public const int padding7 = 2131099674;
			
			// aapt resource value: 0x7f06001c
			public const int padding8 = 2131099676;
			
			// aapt resource value: 0x7f06001e
			public const int padding9 = 2131099678;
			
			// aapt resource value: 0x7f060000
			public const int parent = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int spread = 2131099649;
			
			// aapt resource value: 0x7f060004
			public const int spread_inside = 2131099652;
			
			// aapt resource value: 0x7f060002
			public const int wrap = 2131099650;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int SplashScreenLayout = 2130903041;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Raw
		{
			
			// aapt resource value: 0x7f040000
			public const int SE_test = 2130968576;
			
			static Raw()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Raw()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050000
			public const int app_name = 2131034112;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] ConstraintLayout_Layout = new int[] {
					16842948,
					16843039,
					16843040,
					16843071,
					16843072,
					2130771968,
					2130771969,
					2130771970,
					2130771971,
					2130771972,
					2130771973,
					2130771974,
					2130771975,
					2130771976,
					2130771977,
					2130771978,
					2130771979,
					2130771980,
					2130771981,
					2130771982,
					2130771983,
					2130771984,
					2130771985,
					2130771986,
					2130771987,
					2130771988,
					2130771989,
					2130771990,
					2130771991,
					2130771992,
					2130771993,
					2130771994,
					2130771995,
					2130771996,
					2130771997,
					2130771998,
					2130771999,
					2130772000,
					2130772001,
					2130772002,
					2130772003,
					2130772004,
					2130772005,
					2130772006,
					2130772007,
					2130772008,
					2130772009,
					2130772010,
					2130772011};
			
			// aapt resource value: 2
			public const int ConstraintLayout_Layout_android_maxHeight = 2;
			
			// aapt resource value: 1
			public const int ConstraintLayout_Layout_android_maxWidth = 1;
			
			// aapt resource value: 4
			public const int ConstraintLayout_Layout_android_minHeight = 4;
			
			// aapt resource value: 3
			public const int ConstraintLayout_Layout_android_minWidth = 3;
			
			// aapt resource value: 0
			public const int ConstraintLayout_Layout_android_orientation = 0;
			
			// aapt resource value: 5
			public const int ConstraintLayout_Layout_constraintSet = 5;
			
			// aapt resource value: 6
			public const int ConstraintLayout_Layout_layout_constraintBaseline_creator = 6;
			
			// aapt resource value: 7
			public const int ConstraintLayout_Layout_layout_constraintBaseline_toBaselineOf = 7;
			
			// aapt resource value: 8
			public const int ConstraintLayout_Layout_layout_constraintBottom_creator = 8;
			
			// aapt resource value: 9
			public const int ConstraintLayout_Layout_layout_constraintBottom_toBottomOf = 9;
			
			// aapt resource value: 10
			public const int ConstraintLayout_Layout_layout_constraintBottom_toTopOf = 10;
			
			// aapt resource value: 11
			public const int ConstraintLayout_Layout_layout_constraintDimensionRatio = 11;
			
			// aapt resource value: 12
			public const int ConstraintLayout_Layout_layout_constraintEnd_toEndOf = 12;
			
			// aapt resource value: 13
			public const int ConstraintLayout_Layout_layout_constraintEnd_toStartOf = 13;
			
			// aapt resource value: 14
			public const int ConstraintLayout_Layout_layout_constraintGuide_begin = 14;
			
			// aapt resource value: 15
			public const int ConstraintLayout_Layout_layout_constraintGuide_end = 15;
			
			// aapt resource value: 16
			public const int ConstraintLayout_Layout_layout_constraintGuide_percent = 16;
			
			// aapt resource value: 17
			public const int ConstraintLayout_Layout_layout_constraintHeight_default = 17;
			
			// aapt resource value: 18
			public const int ConstraintLayout_Layout_layout_constraintHeight_max = 18;
			
			// aapt resource value: 19
			public const int ConstraintLayout_Layout_layout_constraintHeight_min = 19;
			
			// aapt resource value: 20
			public const int ConstraintLayout_Layout_layout_constraintHorizontal_bias = 20;
			
			// aapt resource value: 21
			public const int ConstraintLayout_Layout_layout_constraintHorizontal_chainStyle = 21;
			
			// aapt resource value: 22
			public const int ConstraintLayout_Layout_layout_constraintHorizontal_weight = 22;
			
			// aapt resource value: 23
			public const int ConstraintLayout_Layout_layout_constraintLeft_creator = 23;
			
			// aapt resource value: 24
			public const int ConstraintLayout_Layout_layout_constraintLeft_toLeftOf = 24;
			
			// aapt resource value: 25
			public const int ConstraintLayout_Layout_layout_constraintLeft_toRightOf = 25;
			
			// aapt resource value: 26
			public const int ConstraintLayout_Layout_layout_constraintRight_creator = 26;
			
			// aapt resource value: 27
			public const int ConstraintLayout_Layout_layout_constraintRight_toLeftOf = 27;
			
			// aapt resource value: 28
			public const int ConstraintLayout_Layout_layout_constraintRight_toRightOf = 28;
			
			// aapt resource value: 29
			public const int ConstraintLayout_Layout_layout_constraintStart_toEndOf = 29;
			
			// aapt resource value: 30
			public const int ConstraintLayout_Layout_layout_constraintStart_toStartOf = 30;
			
			// aapt resource value: 31
			public const int ConstraintLayout_Layout_layout_constraintTop_creator = 31;
			
			// aapt resource value: 32
			public const int ConstraintLayout_Layout_layout_constraintTop_toBottomOf = 32;
			
			// aapt resource value: 33
			public const int ConstraintLayout_Layout_layout_constraintTop_toTopOf = 33;
			
			// aapt resource value: 34
			public const int ConstraintLayout_Layout_layout_constraintVertical_bias = 34;
			
			// aapt resource value: 35
			public const int ConstraintLayout_Layout_layout_constraintVertical_chainStyle = 35;
			
			// aapt resource value: 36
			public const int ConstraintLayout_Layout_layout_constraintVertical_weight = 36;
			
			// aapt resource value: 37
			public const int ConstraintLayout_Layout_layout_constraintWidth_default = 37;
			
			// aapt resource value: 38
			public const int ConstraintLayout_Layout_layout_constraintWidth_max = 38;
			
			// aapt resource value: 39
			public const int ConstraintLayout_Layout_layout_constraintWidth_min = 39;
			
			// aapt resource value: 40
			public const int ConstraintLayout_Layout_layout_editor_absoluteX = 40;
			
			// aapt resource value: 41
			public const int ConstraintLayout_Layout_layout_editor_absoluteY = 41;
			
			// aapt resource value: 42
			public const int ConstraintLayout_Layout_layout_goneMarginBottom = 42;
			
			// aapt resource value: 43
			public const int ConstraintLayout_Layout_layout_goneMarginEnd = 43;
			
			// aapt resource value: 44
			public const int ConstraintLayout_Layout_layout_goneMarginLeft = 44;
			
			// aapt resource value: 45
			public const int ConstraintLayout_Layout_layout_goneMarginRight = 45;
			
			// aapt resource value: 46
			public const int ConstraintLayout_Layout_layout_goneMarginStart = 46;
			
			// aapt resource value: 47
			public const int ConstraintLayout_Layout_layout_goneMarginTop = 47;
			
			// aapt resource value: 48
			public const int ConstraintLayout_Layout_layout_optimizationLevel = 48;
			
			public static int[] ConstraintSet = new int[] {
					16842948,
					16842960,
					16842972,
					16842996,
					16842997,
					16842999,
					16843000,
					16843001,
					16843002,
					16843551,
					16843552,
					16843553,
					16843554,
					16843555,
					16843556,
					16843557,
					16843559,
					16843560,
					16843701,
					16843702,
					16843770,
					16843840,
					2130771969,
					2130771970,
					2130771971,
					2130771972,
					2130771973,
					2130771974,
					2130771975,
					2130771976,
					2130771977,
					2130771978,
					2130771979,
					2130771980,
					2130771981,
					2130771982,
					2130771983,
					2130771984,
					2130771985,
					2130771986,
					2130771987,
					2130771988,
					2130771989,
					2130771990,
					2130771991,
					2130771992,
					2130771993,
					2130771994,
					2130771995,
					2130771996,
					2130771997,
					2130771998,
					2130771999,
					2130772000,
					2130772001,
					2130772002,
					2130772003,
					2130772004,
					2130772005,
					2130772006,
					2130772007,
					2130772008,
					2130772009,
					2130772010};
			
			// aapt resource value: 9
			public const int ConstraintSet_android_alpha = 9;
			
			// aapt resource value: 21
			public const int ConstraintSet_android_elevation = 21;
			
			// aapt resource value: 1
			public const int ConstraintSet_android_id = 1;
			
			// aapt resource value: 4
			public const int ConstraintSet_android_layout_height = 4;
			
			// aapt resource value: 8
			public const int ConstraintSet_android_layout_marginBottom = 8;
			
			// aapt resource value: 19
			public const int ConstraintSet_android_layout_marginEnd = 19;
			
			// aapt resource value: 5
			public const int ConstraintSet_android_layout_marginLeft = 5;
			
			// aapt resource value: 7
			public const int ConstraintSet_android_layout_marginRight = 7;
			
			// aapt resource value: 18
			public const int ConstraintSet_android_layout_marginStart = 18;
			
			// aapt resource value: 6
			public const int ConstraintSet_android_layout_marginTop = 6;
			
			// aapt resource value: 3
			public const int ConstraintSet_android_layout_width = 3;
			
			// aapt resource value: 0
			public const int ConstraintSet_android_orientation = 0;
			
			// aapt resource value: 16
			public const int ConstraintSet_android_rotationX = 16;
			
			// aapt resource value: 17
			public const int ConstraintSet_android_rotationY = 17;
			
			// aapt resource value: 14
			public const int ConstraintSet_android_scaleX = 14;
			
			// aapt resource value: 15
			public const int ConstraintSet_android_scaleY = 15;
			
			// aapt resource value: 10
			public const int ConstraintSet_android_transformPivotX = 10;
			
			// aapt resource value: 11
			public const int ConstraintSet_android_transformPivotY = 11;
			
			// aapt resource value: 12
			public const int ConstraintSet_android_translationX = 12;
			
			// aapt resource value: 13
			public const int ConstraintSet_android_translationY = 13;
			
			// aapt resource value: 20
			public const int ConstraintSet_android_translationZ = 20;
			
			// aapt resource value: 2
			public const int ConstraintSet_android_visibility = 2;
			
			// aapt resource value: 22
			public const int ConstraintSet_layout_constraintBaseline_creator = 22;
			
			// aapt resource value: 23
			public const int ConstraintSet_layout_constraintBaseline_toBaselineOf = 23;
			
			// aapt resource value: 24
			public const int ConstraintSet_layout_constraintBottom_creator = 24;
			
			// aapt resource value: 25
			public const int ConstraintSet_layout_constraintBottom_toBottomOf = 25;
			
			// aapt resource value: 26
			public const int ConstraintSet_layout_constraintBottom_toTopOf = 26;
			
			// aapt resource value: 27
			public const int ConstraintSet_layout_constraintDimensionRatio = 27;
			
			// aapt resource value: 28
			public const int ConstraintSet_layout_constraintEnd_toEndOf = 28;
			
			// aapt resource value: 29
			public const int ConstraintSet_layout_constraintEnd_toStartOf = 29;
			
			// aapt resource value: 30
			public const int ConstraintSet_layout_constraintGuide_begin = 30;
			
			// aapt resource value: 31
			public const int ConstraintSet_layout_constraintGuide_end = 31;
			
			// aapt resource value: 32
			public const int ConstraintSet_layout_constraintGuide_percent = 32;
			
			// aapt resource value: 33
			public const int ConstraintSet_layout_constraintHeight_default = 33;
			
			// aapt resource value: 34
			public const int ConstraintSet_layout_constraintHeight_max = 34;
			
			// aapt resource value: 35
			public const int ConstraintSet_layout_constraintHeight_min = 35;
			
			// aapt resource value: 36
			public const int ConstraintSet_layout_constraintHorizontal_bias = 36;
			
			// aapt resource value: 37
			public const int ConstraintSet_layout_constraintHorizontal_chainStyle = 37;
			
			// aapt resource value: 38
			public const int ConstraintSet_layout_constraintHorizontal_weight = 38;
			
			// aapt resource value: 39
			public const int ConstraintSet_layout_constraintLeft_creator = 39;
			
			// aapt resource value: 40
			public const int ConstraintSet_layout_constraintLeft_toLeftOf = 40;
			
			// aapt resource value: 41
			public const int ConstraintSet_layout_constraintLeft_toRightOf = 41;
			
			// aapt resource value: 42
			public const int ConstraintSet_layout_constraintRight_creator = 42;
			
			// aapt resource value: 43
			public const int ConstraintSet_layout_constraintRight_toLeftOf = 43;
			
			// aapt resource value: 44
			public const int ConstraintSet_layout_constraintRight_toRightOf = 44;
			
			// aapt resource value: 45
			public const int ConstraintSet_layout_constraintStart_toEndOf = 45;
			
			// aapt resource value: 46
			public const int ConstraintSet_layout_constraintStart_toStartOf = 46;
			
			// aapt resource value: 47
			public const int ConstraintSet_layout_constraintTop_creator = 47;
			
			// aapt resource value: 48
			public const int ConstraintSet_layout_constraintTop_toBottomOf = 48;
			
			// aapt resource value: 49
			public const int ConstraintSet_layout_constraintTop_toTopOf = 49;
			
			// aapt resource value: 50
			public const int ConstraintSet_layout_constraintVertical_bias = 50;
			
			// aapt resource value: 51
			public const int ConstraintSet_layout_constraintVertical_chainStyle = 51;
			
			// aapt resource value: 52
			public const int ConstraintSet_layout_constraintVertical_weight = 52;
			
			// aapt resource value: 53
			public const int ConstraintSet_layout_constraintWidth_default = 53;
			
			// aapt resource value: 54
			public const int ConstraintSet_layout_constraintWidth_max = 54;
			
			// aapt resource value: 55
			public const int ConstraintSet_layout_constraintWidth_min = 55;
			
			// aapt resource value: 56
			public const int ConstraintSet_layout_editor_absoluteX = 56;
			
			// aapt resource value: 57
			public const int ConstraintSet_layout_editor_absoluteY = 57;
			
			// aapt resource value: 58
			public const int ConstraintSet_layout_goneMarginBottom = 58;
			
			// aapt resource value: 59
			public const int ConstraintSet_layout_goneMarginEnd = 59;
			
			// aapt resource value: 60
			public const int ConstraintSet_layout_goneMarginLeft = 60;
			
			// aapt resource value: 61
			public const int ConstraintSet_layout_goneMarginRight = 61;
			
			// aapt resource value: 62
			public const int ConstraintSet_layout_goneMarginStart = 62;
			
			// aapt resource value: 63
			public const int ConstraintSet_layout_goneMarginTop = 63;
			
			public static int[] LinearConstraintLayout = new int[] {
					16842948};
			
			// aapt resource value: 0
			public const int LinearConstraintLayout_android_orientation = 0;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
